---
name: 'Generate Animation Snake'

on:
  push:
    branches:
      - master
  schedule:
    - cron: '0 22,4,10,16 * * *'
  workflow_dispatch:

permissions: 
  contents: write

jobs:
  generate:
    name: 'Generate Animation Snake'
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: 'Generate snake.svg'
        uses: Platane/snk/svg-only@v3.3.0
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/profile-snake-contrib/github-contribution-grid-snake.svg
            dist/profile-snake-contrib/github-contribution-grid-snake-dark.svg?palette=github-dark

      - name: 'Push snake.svg to the output branch'
        uses: crazy-max/ghaction-github-pages@v4.2.0
        with:
          target_branch: output
          build_dir: dist
          commit_message: 'chore: synchronize snake svg commit graph'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}